name: Deploy Project
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code    #downloads code from the repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci #Installs dependencies but uses versions locked into the package-lock.json file(to make sure we use the same versions)
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code    #downloads code from the repository
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci #Installs dependencies but uses versions locked into the package-lock.json file(to make sure we use the same versions)
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ..."
